/*
Created By: Anh Phan
Created Date: 11/24/2019
Purpose: The create customer request strucutre.
----------------------------------------------------------------------------------------------
Modified By:
Modified Date :
Purpose: 
----------------------------------------------------------------------------------------------
*/

public class AddressRecordType {

  
    private String addressline1 = null;
    
    private String addressline2 = null;
    
    private String addressline3 = null;
    
    private String city = null;
    
    private String county = null;
    
    private String state = null;
    
    private String country = null;
    
    private String zipcode = null;
    
    private String spokerecid = null;
    
    private String spokesystemcode = null;
    
    private String byuser = null;
    
    private String status = null;
    
    private String mdmaddressid = null;
    
}