/*
Created By: Anh Phan
Created Date: 11/24/2019
Purpose: The create customer request strucutre.
----------------------------------------------------------------------------------------------
Modified By:
Modified Date :
Purpose: 
----------------------------------------------------------------------------------------------
*/

public class AddressAssignmentRecordType {

    private String objectcode = null;
    
    private String addressusagecode = null;
    
    private String primaryflag = null;
    
    private String status = null;
    
    private String spokerecid = null;
    
    private String spokesystemcode = null;
    
    private String mdmaddressid = null;
    
    private String mdmobjectrefid = null;
    
    private String mdmassignmentid = null;
    
    private AddressRecordType address = null;
    
}