public class Constant {
    
    public static final String CONTACT_NEW_BLANK_CASE_RT                    = System.Label.Contact_New_Blank_Case_RT;
    public static final String ACCOUNT_BUCKET_SUFFIX                        = System.Label.Account_Bucket_Account_Suffix;
    public static final String SERVICE_GROUP_PREFIX                         = System.Label.Service_Territory_Based_Group_Prefix;
    public static final String PUBLIC_GROUP_TYPE                            = 'Regular';
    public static final String WO_CS_RT                                     = System.Label.Work_Order_CS_RecordType_Name;
    public static final String SA_CS_RT                                     = 'Customer_Service';
    public static final String SA_CS_RT_NAME                                = 'Customer Service';
    public static final String TECHSEE_CASE_ORIGIN                          = System.Label.TECHSEE_CASE_ORIGIN;
    public static final String TECHSEE_CASE_INVALID_MSG                     = System.Label.Techsee_Case_Invalid_Error_Msg;
    public static final String CASE_REPLY_TO_ADDRESS		                = System.Label.Case_Reply_To_Email;
    public static final String CASE_STATUS_MERGED			                = System.Label.Case_Status_Merged;
    public static final String CLOSED_CASES_MERGE_ERROR_TEXT                = System.Label.Closed_Cases_Merge_Error_Text;
    public static final String CUSTOMER_NUMBER_ERROR		                = System.Label.Customer_Number_Error;
    public static final String ASSIGNED_BRANCH_ERROR		                = System.Label.Assigned_Branch_Error;
    public static final String CASE_STATUS_COMPLETED		                = System.Label.Case_Status_Completed;
    public static final String CASE_STATUS_PENDING		                    = System.Label.Case_Status_Pending;
    public static final String CASE_STATUS_CANCELLED		                = System.Label.Case_Status_Cancelled;
    public static final String CASE_STATUS_AWAITING_PART_ORDER		        = System.Label.Case_Status_Awaiting_Parts_Order;
    public static final String CASE_STATUS_INACTIVE			                = System.Label.Case_Status_Inactive;
    public static final String CASE_STATUS_CLOSED			                = System.Label.Case_Status_Closed;
    public static final String GROUP_NAME_CX_COMMUNICATION	                = System.Label.Group_Name_CX_Communication;
    public static final String CASE_UPDATE_PERMISSION_ERROR	                = System.Label.Case_Update_Permission_Error;
    public static final String CASE_COMPLETED_EMAIL_TEMPLATE_NAME	        = System.Label.Case_Completed_Email_Template_Name;
    public static final String CASE_CANCELLED_EMAIL_TEMPLATE_NAME	        = System.Label.Case_Completed_Email_Template_Name;
    public static final String ORGWIDE_EMAIL_WHERE_NAME_IS_PELLA_SUPPORT	= System.Label.Orgwide_Email_Where_Name_is_Pella_Support;
    public static final String CASE_ORIGIN_EMAIL			                = System.Label.Case_Origin_Email;
    public static final String CASE_MODIFY_CUSTOM_PERMISSION		        = System.Label.Modify_Closed_or_Cancelled_Cases; //    DA : SCS-320/SCS-382 : 2023.07.25
    //    DA : SCS-320/SCS-382 : 2023.07.26  : Any new fields to be added has to be in lower case only    
    public static final String CASE_EDITABLE_FIELDS_LIST		            = System.Label.Case_Editable_Fields_List;
    public static final String CASE_LINE_RECROD_TYPE_LABOR                  = System.Label.Case_Line_Record_Type_Labor;
    public static final String CASE_LINE_RECROD_TYPE_PARTS                  = System.Label.Case_Line_Record_Type_Parts;
    public static final String CASE_LINE_RECROD_TYPE_SHIPPING               = System.Label.Case_Line_Record_Type_Shipping;
    public static final String KNOWLEDGE_PUBLISH_STATUS                     = 'Active';
    public static final String ORG_ENDPOINT                                 = System.Label.SERVICE_Org_Endpoint;
    public static final String ADDRESS_INSTALL_STATUS                       = 'Install At';
}