/*
Created By: Anh Phan
Created Date: 11/24/2019
Purpose: The create customer request strucutre.
----------------------------------------------------------------------------------------------
Modified By:
Modified Date :
Purpose: 
----------------------------------------------------------------------------------------------
*/

public class ContactRecordType {

    private String spokerecid = null;
    
    private String spokesystemcode = null;
    
    private String primaryflag = null;
    
    private String objectcode = null;
    
    private String byuser = null;
    
    private String status = null;
    
    private String mdmcontactid = null;
    
    private String mdmpartyid = null;
    
    private String mdmobjectrefid = null;
    
}