public class SearchFilterWrapper {

    @AuraEnabled
    public String firstName;
    @AuraEnabled
    public String lastName;
    @AuraEnabled
    public String accountName;
    @AuraEnabled
    public String phoneNo;
    @AuraEnabled
    public String emailId;
    @AuraEnabled
    public String street;
    @AuraEnabled
    public String city;
    @AuraEnabled
    public String state;
    @AuraEnabled
    public String zipCode;
}