public class businessDaysCalculator {
	/*public static Integer calculateBusinessDays(Date fromDate, Date toDate) {
        CalcBusinessDays calcBusinessDays = new CalcBusinessDays();
        
        // Get non-business days between the provided dates
        List<Date> nonBusinessDays = calcBusinessDays.getNonBusinessDaysBetweenDates(fromDate, toDate);
        
        // Calculate the number of days excluding non-business days (Sundays in this case)
        Integer totalDays = fromDate.daysBetween(toDate) + 1; // Including both fromDate and toDate
        Integer businessDays = totalDays - nonBusinessDays.size();
        
        return businessDays;
    }*/
}